# Generated by Django 4.2.2 on 2023-06-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('detalleId', models.AutoField(primary_key=True, serialize=False)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name': 'Detalle de las facturas emitidas por el hotel correspondientes a las resvervas',
                'verbose_name_plural': 'Detalles',
                'db_table': 'Detalle',
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('detallePagoId', models.AutoField(primary_key=True, serialize=False)),
                ('tipoPago', models.CharField(max_length=100)),
                ('porcentajePago', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Detalle de pago de las facturas emitidas por el hotel',
                'verbose_name_plural': 'Detalles de pago',
                'db_table': 'DetallePagp',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('facturaId', models.AutoField(primary_key=True, serialize=False)),
                ('nroFactura', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Facturas emitidas por el hotel correspondientes a las resvervas',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Factura',
            },
        ),
    ]
