# Generated by Django 4.2.2 on 2023-06-20 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionUsuarios', '0001_initial'),
        ('GestionReservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usuarioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='hotelId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.hotel'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='imagenes',
            field=models.ManyToManyField(to='GestionReservas.imagen'),
        ),
    ]
